### ISSUE TITLE
Running locally will give invalid tableName value

### ISSUE THREAD

**Issue by shawnmclean** [AnomalyInnovations/serverless-stack-demo-mono-api#1]
If this is adapted to test locally, when the function starts, the `process.env.tableName` will be `[Object object]`.

https://github.com/AnomalyInnovations/serverless-stack-demo-mono-api/blob/master/services/notes/serverless.yml#L18

Is there anyway to adapt this line so it conditionally sets the value to something else if we detect that no cloud formation is involved?

**Comment by jayair** [comment]
Yeah we are looking into the issue. Will report back!

**Comment by jayair** [comment]
@shawnmclean We rolled out some updates to address this. The cleanest way we could address this was to import the table name from the DynamoDB service `serverless.yml` like so:

https://github.com/AnomalyInnovations/serverless-stack-demo-mono-api/blob/master/services/users/serverless.yml#L24
